### DISCUSSION TITLE
v3.6.1

### DISCUSSION THREAD

**Discussion by Tochemey** [Tochemey/goakt#775] [Announcements]
## 🚀 What Changed

- **Simplified NATs and Kubernetes discovery configuration**:
  - 🗑️ Deprecated the following settings:
    - `ActorSystemName`: No longer required. Will be removed in future releases.
    - `ApplicationName`: No longer required. Will be removed in future releases.
  - 🔧 Kubernetes-specific configuration changes:
    - The following pod labels are no longer required:
      ```yaml
      app.kubernetes.io/part-of: <actor-system-name>
      app.kubernetes.io/component: <application-name>
      app.kubernetes.io/name: <application-name>
      ```
    - ✅ Use the `PodLabels` field instead to define discovery metadata.

- **`NoSender` Support**:  
  - Messages can now be sent using `NoSender`, making actor communication more ergonomic in certain contexts.

- **Additional Enhancements**:
  - Various code cleanups and internal improvements for better stability and maintainability.
    

## ✅ Pull Requests
* refactor: handle context cancelation or deadline in ask by @Tochemey in https://github.com/Tochemey/goakt/pull/772
* refactor: simplify NATs and K8s configuration by @Tochemey in https://github.com/Tochemey/goakt/pull/773
* refactor: make NoSender an actor instead of nil by @Tochemey in https://github.com/Tochemey/goakt/pull/774

**Full Changelog**: https://github.com/Tochemey/goakt/compare/v3.6.0...v3.6.1

<hr /><em>This discussion was created from the release <a href='https://github.com/Tochemey/goakt/releases/tag/v3.6.1'>v3.6.1</a>.</em>
